image: python:3.5

grade_week_1_mandatory:
  script:
    - cd week_1
    - python form_m1.py
    - python form_m2.py
    - python form_m3.py
  only:
    - /^lab-.*-1$/
  except:
    - master
    - branches@CSUI-AdvProg-2017/lab-exercises
  allow_failure: false

grade_week_1_additional:
  script:
    - cd week_1
    - python form_a1.py
  only:
    - /^lab-.*-1$/
  except:
    - master
    - branches@CSUI-AdvProg-2017/lab-exercises
  allow_failure: true

grade_week_2_mandatory:
  script:
    - cd week_2/factory-method-pattern
    - python Tutorial2-FM.py
    - cd ../singleton-pattern
    - python SingletonPattern.py
    - python NewSingleton.py
    - cat SingletonVsNewSingleton.txt
    - python Tutorial2Singleton.py
  only:
    - /^lab-.*-2$/
  except:
    - master
    - branches@CSUI-AdvProg-2017/lab-exercises
  allow_failure: false

grade_week_2_additional:
  script:
    - cd week_2/factory-method-pattern
    - python Tutorial2-FM-Dynamic.py
    - cat factoryMethodPattern.txt
  only:
    - /^lab-.*-2$/
  except:
    - master
    - branches@CSUI-AdvProg-2017/lab-exercises
  allow_failure: true
