image: python:3.5

teaching-team-test:
  script:
    - python -m unittest discover --verbose week_3
    - python -m unittest discover --verbose week_4
    - python -m unittest discover --verbose week_5
    - python -m unittest discover --verbose week_6
    - python -m unittest discover --verbose week_7
  except:
    - master@CSUI-AdvProg-2017/lab-exercises
  allow_failure: true

student-test-week-3:
  script:
    - python -m unittest discover --verbose week_3
  only:
    - /^lab-.*-3$/
  except:
    - master@CSUI-AdvProg-2017/lab-exercises
    - branches@CSUI-AdvProg-2017/lab-exercises

student-test-week-4:
  script:
    - python -m unittest discover --verbose week_4
  only:
    - /^lab-.*-4$/
  except:
    - master@CSUI-AdvProg-2017/lab-exercises
    - branches@CSUI-AdvProg-2017/lab-exercises

student-test-week-5:
  script:
    - python -m unittest discover --verbose week_5
  only:
    - /^lab-.*-5$/
  except:
    - master@CSUI-AdvProg-2017/lab-exercises
    - branches@CSUI-AdvProg-2017/lab-exercises

student-test-week-6:
  script:
    - python -m unittest discover --verbose week_6
  only:
    - /^lab-.*-6$/
  except:
    - master@CSUI-AdvProg-2017/lab-exercises
    - branches@CSUI-AdvProg-2017/lab-exercises

student-test-week-7:
  script:
    - python -m unittest discover --verbose week_7
  only:
    - /^lab-.*-7$/
  except:
    - master@CSUI-AdvProg-2017/lab-exercises
    - branches@CSUI-AdvProg-2017/lab-exercises
